import React from 'react';
import { 
  Settings, 
  Settings2,
  LayoutDashboard, 
  BarChart3, 
  FilePieChart, 
  TrendingUp,
  Truck,
  Package,
  MapPin,
  Eye,
  ShieldAlert,
  Radio,
  MessageSquare,
  HelpCircle,
  Inbox,
  Award,
  CheckCircle2,
  FileText,
  LifeBuoy,
  Wrench,
  MessageCircle,
  Megaphone,
  Mail,
  Phone,
  UserCircle,
  Heart,
  GraduationCap,
  BarChart4,
  PieChart,
  LineChart,
  UserCheck,
  ClipboardCheck,
  ThumbsUp,
  FileSearch,
  Box,
  Layers,
  ListTodo,
  Shield,
  UserRound,
  Globe
} from 'lucide-react';

export const modules = [
  { id: 'administracion', label: 'Administración', icon: <Shield size={18} /> },
  { id: 'operacion', label: 'Operación', icon: <Settings2 size={18} /> },
  { id: 'tareas', label: 'Tareas', icon: <ListTodo size={18} /> },
  { id: 'reportes', label: 'Reportes', icon: <BarChart3 size={18} /> },
  { id: 'logistica', label: 'Logística', icon: <Truck size={18} /> },
  { id: 'vigilancia', label: 'Vigilancia', icon: <Eye size={18} /> },
  { id: 'pqrs', label: 'PQRS', icon: <MessageSquare size={18} /> },
  { id: 'calidad', label: 'Calidad', icon: <Award size={18} /> },
  { id: 'soporte', label: 'Soporte', icon: <LifeBuoy size={18} /> },
  { id: 'comunicaciones', label: 'Comunicaciones', icon: <Globe size={18} /> },
  { id: 'gestion_humana', label: 'Gestión Humana', icon: <UserRound size={18} /> },
];

export const menuData: Record<string, { label: string; icon: React.ReactNode; path: string }[]> = {
  administracion: [
    { label: 'Dashboard', icon: <LayoutDashboard size={20} />, path: '/admin/dashboard' },
    { label: 'Ind. Gerenciales', icon: <BarChart4 size={20} />, path: '/admin/ind-gerenciales' },
    { label: 'Ind. PQRS', icon: <PieChart size={20} />, path: '/admin/ind-pqrs' },
    { label: 'Ind. de Uso', icon: <LineChart size={20} />, path: '/admin/ind-uso' },
    { label: 'Gestión Clientes', icon: <UserCheck size={20} />, path: '/admin/gestion-clientes' },
    { label: 'Reporte Gestión', icon: <FilePieChart size={20} />, path: '/admin/reporte-gestion' },
    { label: 'Chequeo Supervisión', icon: <ClipboardCheck size={20} />, path: '/admin/supervision' },
    { label: 'Recomendaciones', icon: <MessageSquare size={20} />, path: '/admin/recom' },
    { label: 'Satisfacción', icon: <ThumbsUp size={20} />, path: '/admin/satisfaccion' },
    { label: 'Documentación', icon: <FileText size={20} />, path: '/admin/docs' },
  ],
  operacion: [
    { label: 'Dashboard', icon: <LayoutDashboard size={20} />, path: '/oper/dashboard' },
    { label: 'Items', icon: <Layers size={20} />, path: '/oper/items' },
    { label: 'Cotizaciones', icon: <FilePieChart size={20} />, path: '/oper/cotizaciones' },
    { label: 'Kits', icon: <Box size={20} />, path: '/oper/kits' },
    { label: 'Configuraciones', icon: <Settings size={20} />, path: '/oper/config' },
    { label: 'Documentación', icon: <FileSearch size={20} />, path: '/oper/docs' },
  ],
  tareas: [
    { label: 'Dashboard', icon: <LayoutDashboard size={20} />, path: '/tasks/dashboard' },
    { label: 'Tareas', icon: <ListTodo size={20} />, path: '/tasks/list' },
    { label: 'Documentación', icon: <FileText size={20} />, path: '/tasks/docs' },
  ],
  logistica: [
    { label: 'Dashboard', icon: <LayoutDashboard size={20} />, path: '/logistics/dashboard' },
    { label: 'Flotas', icon: <Truck size={20} />, path: '/logistics/fleet' },
    { label: 'Inventario', icon: <Package size={20} />, path: '/logistics/inventory' },
    { label: 'Rutas', icon: <MapPin size={20} />, path: '/logistics/routes' },
  ],
  vigilancia: [
    { label: 'Dashboard', icon: <LayoutDashboard size={20} />, path: '/security/dashboard' },
    { label: 'Monitoreo', icon: <Eye size={20} />, path: '/security/monitor' },
    { label: 'Alertas', icon: <ShieldAlert size={20} />, path: '/security/alerts' },
    { label: 'Radio', icon: <Radio size={20} />, path: '/security/radio' },
  ],
  pqrs: [
    { label: 'Dashboard', icon: <LayoutDashboard size={20} />, path: '/pqrs/dashboard' },
    { label: 'Recibidos', icon: <Inbox size={20} />, path: '/pqrs/inbox' },
    { label: 'Chat', icon: <MessageSquare size={20} />, path: '/pqrs/chat' },
    { label: 'FAQs', icon: <HelpCircle size={20} />, path: '/pqrs/faqs' },
  ],
  calidad: [
    { label: 'Dashboard', icon: <LayoutDashboard size={20} />, path: '/quality/dashboard' },
    { label: 'Certificaciones', icon: <Award size={20} />, path: '/quality/certs' },
    { label: 'Auditoría', icon: <CheckCircle2 size={20} />, path: '/quality/audit' },
    { label: 'Documentos', icon: <FileText size={20} />, path: '/quality/docs' },
  ],
  soporte: [
    { label: 'Dashboard', icon: <LayoutDashboard size={20} />, path: '/support/dashboard' },
    { label: 'Soporte IT', icon: <LifeBuoy size={20} />, path: '/support/it' },
    { label: 'Mantenimiento', icon: <Wrench size={20} />, path: '/support/mt' },
    { label: 'Ticket', icon: <MessageCircle size={20} />, path: '/support/tickets' },
  ],
  comunicaciones: [
    { label: 'Dashboard', icon: <LayoutDashboard size={20} />, path: '/comms/dashboard' },
    { label: 'Anuncios', icon: <Megaphone size={20} />, path: '/comms/announcements' },
    { label: 'Email', icon: <Mail size={20} />, path: '/comms/email' },
    { label: 'Directorio', icon: <Phone size={20} />, path: '/comms/directory' },
  ],
  gestion_humana: [
    { label: 'Dashboard', icon: <LayoutDashboard size={20} />, path: '/hr/dashboard' },
    { label: 'Empleados', icon: <UserCircle size={20} />, path: '/hr/employees' },
    { label: 'Beneficios', icon: <Heart size={20} />, path: '/hr/benefits' },
    { label: 'Formación', icon: <GraduationCap size={20} />, path: '/hr/training' },
  ],
  reportes: [
    { label: 'Dashboard', icon: <LayoutDashboard size={20} />, path: '/reports/dashboard' },
    { label: 'Resumen', icon: <BarChart3 size={20} />, path: '/reports/summary' },
    { label: 'Exportar', icon: <FilePieChart size={20} />, path: '/reports/export' },
    { label: 'Métricas', icon: <TrendingUp size={20} />, path: '/reports/metrics' },
  ],
};
